name: msvc

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'kengine'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'kengine'
  workflow_dispatch:

jobs:
  debug:
    uses: phisko/cmake-cxx-conan/.github/workflows/test.yml@main
    with:
      os: windows-latest
      configuration: Debug

  release:
    uses: phisko/cmake-cxx-conan/.github/workflows/package.yml@main
    with:
      os: windows-latest
      configuration: Release
